=== ansh1243/jDTO-Binder/src/main/resources/jdto-1.0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://juancavallotti.com/jdto/1.0"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://juancavallotti.com/jdto/1.0">
    
    <!-- the root element -->
    <xsd:element name="dto-mapping">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <!-- can contain a list of zero to many dto elements -->
                    <xsd:element ref="dto" /> 
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
    <!-- the dto element -->
    <xsd:element name="dto">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <!-- can containa a list of source names -->
                    <xsd:element ref="sourceNames" maxOccurs="1" /> 
                    <!-- can containa a list of source fields -->
                    <xsd:element ref="field" />
                </xsd:choice>
            </xsd:sequence>
            <!-- this is the type of the dto required -->
            <xsd:attribute name="type" type="xsd:string" use="required" />
        </xsd:complexType>
    </xsd:element>
    <!-- the field element -->
    <xsd:element name="field">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice>
                    <xsd:choice minOccurs="0" maxOccurs="unbounded">
                        <!-- can contain a list of soruce elements -->
                        <xsd:element ref="source" />
                    </xsd:choice>
                </xsd:choice>
            </xsd:sequence>
            <!-- the attributes of the field -->
            <xsd:attribute name="name" type="xsd:string" />
            <xsd:attribute name="merger" type="xsd:string" />
            <xsd:attribute name="mergerParam" type="xsd:string" />
            <xsd:attribute name="transient" type="xsd:boolean" />
            <xsd:attribute name="cascade" type="xsd:boolean" />
        </xsd:complexType>
    </xsd:element>
    <!-- the source element -->
    <xsd:element name="source">
        <xsd:complexType>
            <xsd:attribute name="name" type="xsd:string" />
            <xsd:attribute name="bean" type="xsd:string" />
            <xsd:attribute name="merger" type="xsd:string" />
            <xsd:attribute name="mergerParam" type="xsd:string" />
        </xsd:complexType>
    </xsd:element>
    <!-- the bean name element, for naming source beans -->
    <xsd:element name="beanName" type="xsd:string" />
    <!-- the source names element, for multi bean source -->
    <xsd:element name="sourceNames">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element ref="beanName" />
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== ansh1243/jDTO-Binder/src/main/resources/demoxml.xml
<?xml version="1.0" encoding="UTF-8"?>
<dto-mapping 
    xmlns="http://juancavallotti.com/jdto/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://juancavallotti.com/jdto/1.0 jdto-1.0.xsd">
        
        <dto type="com.juancavallotti.PersonDTO">
            <sourceNames>
                <beanName>bean1</beanName>
                <beanName>bean2</beanName>
                <beanName>bean3</beanName>
            </sourceNames>
            <field name="personAge" cascade="true" >
                <source name="test" bean="bean1" />
            </field>
        </dto>
</dto-mapping>

=== ansh1243/jDTO-Binder/jdto/src/test/resources/xmlmappingtest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
/*
 *    Copyright 2012 Juan Alberto LÃ³pez Cavallotti
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
-->
<dto-mapping 
    xmlns="http://jdto.org/jdto/1.0" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://jdto.org/jdto/1.0 
        http://jdto.org/jdto-1.0.xsd">
    
    <!-- to test simple binding -->
    <dto type="org.jdto.dtos.XMLTesterDTO">
            
        <field name="aString" transient="true" />
        
        <!-- A field bound to another field. -->
        <field name="dtoName">
            <source name="aString" />
        </field>
    </dto>
    <!-- to test cascade logic -->
    <dto type="org.jdto.dtos.ComplexDTO">
        <field name="cascadedField" cascade="true">
            <source name="association" />
        </field>
        <field name="stringField">
            <source name="name" />
        </field>
    </dto>
    
    <!-- test the association feature -->
    <dto type="org.jdto.dtos.SimpleAssociationDTO">
        <field name="firstString">
            <source name="myString" />
        </field>
        <field name="secondString">
            <source name="related.aString" />
        </field>
    </dto>
        
    <!-- test the compound merger feature -->
    <dto type="org.jdto.dtos.FormatDTO">
        <!-- single field merger test -->
        <field  name="price">
            <source name="aDouble" 
            merger="org.jdto.mergers.StringFormatMerger"
            mergerParam="$ %.2f" />
        </field>
        <!-- multiple field merger test -->
        <field name="compound" mergerParam="%.2f %08d" 
        merger="org.jdto.mergers.StringFormatMerger">
            <source name="aDouble" />
            <source name="anInt" /> 
        </field>
    </dto>
    
    <!-- test the multi source feature -->
    <dto type="org.jdto.dtos.MultiSourceDTO">
        <sourceNames>
            <beanName>bean1</beanName>
            <beanName>bean2</beanName>
            <beanName>bean3</beanName>
        </sourceNames>
        <field name="source1">
            <source name="aString" bean="bean1" />
        </field>
        <field name="source2">
            <source name="aString" bean="bean2" />
        </field>
        <field name="source3">
            <source name="aString" bean="bean3" />
        </field>
    </dto>
    
    <!-- test immutable simple case -->
    <dto type="org.jdto.dtos.SimpleImmutableDTO">
        <immutableConstructor>
            <arg type="java.lang.String">
                <source name="myString" />
            </arg>
            <arg type="java.lang.String">
                <source name="related.aString" />
            </arg>
        </immutableConstructor>
    </dto>
</dto-mapping>
